# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180730_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plt_icon',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
